export default function Disclaimer() {
  const sections = [
    {
      title: '1. Forward-Looking Statements',
      body: 'This website contains forward-looking statements within the meaning of applicable securities and financial communications laws. These statements relate to future events, projections, estimates, business plans, and anticipated performance of RevFlex and properties that may be financed through RevFlex programs. Forward-looking statements are identifiable by the use of words such as "may," "will," "expect," "anticipate," "estimate," "project," "intend," "plan," "believe," "potential," "illustrative," and similar expressions.'
    },
    {
      title: '2. No Guarantee of Results',
      body: 'All financial projections, revenue uplift estimates, RevPAR improvement ranges, payback period estimates, and other performance metrics displayed on this website — including those generated by the RevFlex estimate calculator — are illustrative only. They are based on historical market data, comparable property benchmarks, and internal modeling assumptions. Actual results may differ materially from any projections or estimates provided. Past performance of comparable properties is not indicative of future results.'
    },
    {
      title: '3. Risks and Uncertainties',
      body: 'Forward-looking statements are subject to significant risks, uncertainties, and assumptions that could cause actual outcomes to differ materially from those described. These include, but are not limited to: general economic and market conditions; changes in hospitality industry demand; competitive pressures; changes in interest rates and capital markets; the ability of a property to execute planned improvements on time and on budget; changes in consumer behavior and travel patterns; weather, natural disasters, and force majeure events; regulatory changes; and the ability of RevFlex to deploy capital on expected terms.'
    },
    {
      title: '4. Calculator and Estimate Outputs',
      body: 'The RevFlex estimate calculator generates illustrative financing estimates based solely on the inputs provided by the user. These estimates do not constitute pre-qualification, pre-approval, or any commitment to lend. Actual financing amounts, revenue share rates, repayment caps, grace periods, and other terms are determined through RevFlex\'s full underwriting and review process and may differ materially from calculator outputs. RevFlex makes no representation that any property will qualify for financing.'
    },
    {
      title: '5. No Investment Advice',
      body: 'Nothing on this website constitutes investment advice, financial advice, tax advice, or legal advice. RevFlex is not a registered investment advisor, broker-dealer, or bank. Users should consult their own financial, legal, and tax advisors before making any decisions related to property improvement financing or capital structures.'
    },
    {
      title: '6. No Obligation to Update',
      body: 'RevFlex undertakes no obligation to publicly update or revise any forward-looking statements, whether as a result of new information, future events, or otherwise. All forward-looking statements on this website speak only as of the date on which they are made.'
    },
    {
      title: '7. Contact',
      body: 'If you have questions about these disclosures, please contact us at hello@revflex.co.'
    },
  ]

  return (
    <main style={{ fontFamily: "'Inter', sans-serif", background: '#FAF8F4', color: '#1A1D1A', minHeight: '100vh' }}>
      <nav style={{ borderBottom: '1px solid #E8E4DE', padding: '0 32px', height: '64px', display: 'flex', alignItems: 'center' }}>
        <a href="/" style={{ fontFamily: "'Libre Baskerville', serif", fontSize: '20px', color: '#1A1D1A', textDecoration: 'none' }}>RevFlex</a>
      </nav>
      <div style={{ maxWidth: '720px', margin: '0 auto', padding: '72px 32px' }}>
        <div style={{ fontSize: '11px', letterSpacing: '0.18em', textTransform: 'uppercase', color: '#9A8A7A', marginBottom: '16px', fontWeight: '600' }}>Legal</div>
        <h1 style={{ fontFamily: "'Libre Baskerville', serif", fontSize: 'clamp(28px, 4vw, 44px)', fontWeight: '400', marginBottom: '12px', lineHeight: '1.2' }}>Forward-Looking Statements</h1>
        <p style={{ fontSize: '13px', color: '#9A8A7A', marginBottom: '48px' }}>Last updated: May 2026</p>
        {sections.map(({ title, body }) => (
          <div key={title} style={{ marginBottom: '36px' }}>
            <h2 style={{ fontFamily: "'Libre Baskerville', serif", fontSize: '18px', fontWeight: '400', color: '#1A1D1A', marginBottom: '10px' }}>{title}</h2>
            <p style={{ fontSize: '15px', lineHeight: '1.8', color: '#4A4E4A', margin: 0 }}>{body}</p>
          </div>
        ))}
        <div style={{ marginTop: '48px', paddingTop: '32px', borderTop: '1px solid #E8E4DE' }}>
          <a href="/" style={{ fontSize: '14px', color: '#C27C4E', textDecoration: 'none' }}>← Back to RevFlex</a>
        </div>
      </div>
    </main>
  )
}

